# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (c) 2026 Cledoo
from . import test_installed
from . import test_jsonrpc
from . import test_auth
from . import test_auth_lib
from . import test_tools_acl
from . import test_gateway
from . import test_controller_lite
from . import test_controller_hardening
from . import test_settings
from . import test_oauth_tokens
from . import test_oauth_models
from . import test_oauth_discovery
from . import test_oauth_flow
from . import test_oauth_token
from . import test_auth_resolve_bearer
from . import test_oauth_admin
from . import test_oauth_gc
from . import test_params
from . import test_arg_coercion
from . import test_download_urls
from . import test_oauth_ttl
from . import test_tools_context
from . import test_tools_errors
from . import test_multicompany
from . import test_ratelimit
from . import test_activity
from . import test_health
from . import test_telemetry
from . import test_tools_aggregate
from . import test_tools_modules
from . import test_tools_chatter
from . import test_tools_export
from . import test_tools_report
from . import test_mcp_label
from . import test_tools_resource
from . import test_sessions
from . import test_seam_scope_hooks
from . import test_telemetry_seam
from . import test_tool_error_results
from . import test_record_urls
